import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Navigation } from '@/components/Navigation';
import { ThemeSwitcher } from '@/components/ThemeSwitcher';
import { ThemeProvider } from '@/provider/ThemeProvider';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const font = Roboto({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-roboto',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen flex justify-center">
        <ThemeProvider attribute="class" defaultTheme="system">
          <div
            className={cn('flex flex-col items-center max-w-lg w-full pt-8 z-10', font.variable)}
          >
            <Navigation />
            <div className="w-full bg-slate-500 dark:bg-gray-300 lime:bg-gray-800 flex-1 text-white dark:text-slate-800 p-4">
              {children}
            </div>
          </div>
          <object
            className="absolute opacity-40 z-0 w-screen h-screen"
            type="image/svg+xml"
            data="/lucca.svg"
          />
          <div className="absolute top-4 right-10">
            <ThemeSwitcher />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
